[workspace]
authors = ["Byron Burks <sixthbaron9@protonmail.com>"]
channels = ["conda-forge"]
name = "fastapi"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
starlette = ">=0.40.0,<0.47.0"
pydantic = ">=1.7.4,!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0"
typing-extensions = ">=4.8.0"
httpx = ">=0.23.0"
jinja2 = ">=3.1.5"
python-multipart = ">=0.0.18"
itsdangerous = ">=1.1.0"
fastapi-cli = ">=0.0.5"
pyyaml = ">=5.3.1"
ujson = ">=4.0.1,!=4.0.2,!=4.1.0,!=4.2.0,!=4.3.0,!=5.0.0,!=5.1.0"
orjson = ">=3.2.1"
email-validator = ">=2.0.0"
uvicorn = ">=0.12.0"
pydantic-settings = ">=2.0.0"
pydantic-extra-types = ">=2.0.0"
typer = ">=0.16.0,<0.17"
pre-commit = ">=2.17.0,<5.0.0"
playwright = ">=1.52.0,<2"

[environments]
test = {features = ["test"], solve-group = "test"}
docs = {features = ["docs"], solve-group = "docs"}

[tasks]
launch-cli = "fastapi run fastapi.cli:main"
format-code = "bash scripts.format.sh"

[feature.test.dependencies]
pytest = ">=7.1.3,<9.0.0"
coverage = ">=6.5.0,<8.0"
mypy = "==1.8.0"
dirty-equals = "==0.9.0"
sqlmodel = "==0.0.24"
flask = ">=1.1.2,<4.0.0"
anyio = ">=3.2.1,<5.0.0"
PyJWT = "==2.8.0"
pyyaml = ">=5.3.1,<7.0.0"
passlib = ">=1.7.2,<2.0.0"
inline-snapshot = ">=0.21.1"
# types
types-ujson = "==5.10.0.20240515"
types-orjson = "==3.6.2"

[feature.test.tasks]
test-code = "bash scripts/test.sh"

[feature.docs.dependencies]
mkdocs-material = "==9.6.1"
mkdocs-redirects = ">=1.2.1,<1.3.0"
typer = "==0.16.0"
pyyaml = ">=5.3.1,<7.0.0"
# For Material for MkDocs, Chinese search
jieba = "==0.42.1"
# For image processing by Material for MkDocs
pillow = "==11.1.0"
# For image processing by Material for MkDocs
cairosvg = "==2.7.1"
mkdocstrings = "==0.26.1"
# For griffe, it formats with black
black = "==25.1.0"
mkdocs-macros-plugin = "==1.3.7"

[feature.docs.pypi-dependencies]
markdown-include-variants = ">=0.0.4, <0.0.5"

[feature.docs.tasks]
live-docs = "python ./scripts/docs.py live"
